conflicts:
- file: er-diagram.yml
  id: Category
  action: overwrite
- file: er-diagram.yml
  id: AttributeDef
  action: overwrite
- file: er-diagram.yml
  id: AttributeSet
  action: overwrite
- file: er-diagram.yml
  id: AttributeSetItem
  action: overwrite
- file: er-diagram.yml
  id: Product
  action: overwrite
- file: er-diagram.yml
  id: Sku
  action: overwrite
- file: er-diagram.yml
  id: Customer
  action: overwrite
- file: er-diagram.yml
  id: Order
  action: overwrite
- file: er-diagram.yml
  id: Refund
  action: overwrite
- file: state-machine.yml
  id: attribute_visibility_cycle
  action: overwrite
- file: state-machine.yml
  id: product_lifecycle
  action: overwrite
- file: state-machine.yml
  id: order_lifecycle
  action: overwrite
- file: state-machine.yml
  id: payment_lifecycle
  action: overwrite
- file: state-machine.yml
  id: refund_lifecycle
  action: overwrite
- file: business-flow.yml
  id: refund_flow
  action: overwrite
generated_at: '2026-06-16T06:54:22Z'
