[package]
name = "marketing"
version.workspace = true
edition.workspace = true

[dependencies]
common = { workspace = true }
identity = { workspace = true }
infra = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sea-orm = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
hmac = "0.12"
thiserror = { workspace = true }
redis = { workspace = true }
uuid = { workspace = true }
inventory = "0.3"
sha2 = "0.10"
base64 = "0.22"
rust_decimal = "1.43.0"
