//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "login_history")]
pub struct Model {
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: Option<i64>,
    pub email: Option<String>,
    pub method: i8,
    pub ip: Option<String>,
    pub device: Option<String>,
    pub location: Option<String>,
    pub result: i8,
    pub is_new_device: i8,
    pub notified: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
