//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod admin_session;
pub mod admin_user;
pub mod auth_config;
pub mod login_history;
pub mod otp_code;
pub mod permission;
pub mod role;
pub mod role_permission;
pub mod user;
pub mod user_identity;
pub mod user_session;
