//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::admin_session::Entity as AdminSession;
pub use super::admin_user::Entity as AdminUser;
pub use super::auth_config::Entity as AuthConfig;
pub use super::login_history::Entity as LoginHistory;
pub use super::otp_code::Entity as OtpCode;
pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::user::Entity as User;
pub use super::user_identity::Entity as UserIdentity;
pub use super::user_session::Entity as UserSession;
