//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_session")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_id: u64,
    #[sea_orm(unique)]
    pub token_id: String,
    pub refresh_token_id: Option<String>,
    pub access_expires_at: Option<DateTime>,
    pub refresh_expires_at: Option<DateTime>,
    pub device: Option<String>,
    pub browser: Option<String>,
    pub ip: Option<String>,
    pub location: Option<String>,
    pub is_new_device: i8,
    pub method: i8,
    pub status: i8,
    pub last_active_at: Option<DateTime>,
    pub version: i32,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
