//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_identity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: u64,
    pub provider: i8,
    pub provider_uid: String,
    pub identifier: Option<String>,
    pub is_primary: i8,
    pub verified: i8,
    pub connected: i8,
    pub hidden_email: i8,
    pub relay_email: Option<String>,
    pub relay_valid: Option<i8>,
    pub bound_at: Option<DateTime>,
    pub last_login_at: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
