//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    #[sea_orm(primary_key)]
    pub id: u64,
    #[sea_orm(unique)]
    pub email: String,
    pub email_verified: i8,
    pub locale_pref: Option<String>,
    pub name: Option<String>,
    pub phone: Option<String>,
    pub tier: i8,
    pub status: i8,
    pub avatar: Option<String>,
    pub joined_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
    pub anonymized: i8,
    pub anonymized_at: Option<DateTime>,
    pub version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
